### PR TITLE
Upgrade to Erlang 24x (Final)

### PR DESCRIPTION
**Pull request by lbakerchef**
This goes with the 'final' Erlang upgrade PR.

Summary:

- Update `rebar3`
- Use Erlang24 for verify pipeline

Depends on: https://github.com/chef/chef-server/pull/3206

### CODE REVIEW

**Comment by marcparadise** [comment]
The new commit looks fine, but that package doesn't seem to exist yet.

**Comment by lbakerchef** [comment]
> The new commit looks fine, but that package doesn't seem to exist yet.

Yup, trying to get that added.

**Review by marcparadise — APPROVED** [review]

**Comment by lbakerchef** [comment]
hab packages added:
https://buildkite.com/chef-oss/chef-mini-s3-main-verify/builds/65

**Review by vinay-satish — APPROVED** [review]
LGTM!

**Pull request merged**
